version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'