on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Client Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./FrontEnd
          push: true
          tags: sevithan/ieee_pes:frontend
          dockerfile: ./FrontEnd/Dockerfile
          registry: docker.io

      - name: Build and push Server Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./BackEnd
          push: true
          tags: sevithan/ieee_pes:backend
          dockerfile: ./BackEnd/Dockerfile
          registry: docker.io

      - name: Deploy Services with Docker Compose
        run: |
          docker-compose -f ./docker-compose.yml up -d
        working-directory: ${{ github.workspace }}